server:
  port: 8000
  error:
    include-message: always
  servlet:
    context-path: /white-rabbit

spring:
  application:
    name: White Rabbit
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/shared
    username: white_rabbit
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

files-manager-url: http://localhost:10500/files-manager

fake-data-db:
  db-type: PostgreSQL
  server: localhost
  port: 5432
  database: source
  user: source
  password: password