server:
  port: 8000
  error:
    include-message: always
  servlet:
    context-path: /white-rabbit

spring:
  application:
    name: White Rabbit
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${SHARED_DB_URL}
    username: ${SHARED_DB_WR_USERNAME}
    password: ${SHARED_DB_WR_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false

files-manager-url: ${FILE_MANAGER_URL}

fake-data-db:
  db-type: ${SOURCE_DB_TYPE}
  server: ${SOURCE_DB_HOST}
  port: ${SOURCE_DB_PORT}
  database: ${SOURCE_DB_NAME}
  user: ${SOURCE_DB_USER}
  password: ${SOURCE_DB_PASSWORD}